import { describe, expect, it } from 'vitest'
import { carveGlyph, glyphForSkin } from './skins'

describe('carveGlyph', () => {
  it('plants a foot shadow, crown sheen, and lamp-lit body on a raw Staunton svg', () => {
    const raw = '<svg class="svg-piece" viewBox="0 0 45 45"><path fill="var(--piece-fill)" d="M1"/></svg>'
    const carved = carveGlyph(raw, 'w')
    expect(carved).toContain('class="piece-foot"')
    expect(carved).toContain('class="piece-carve"')
    expect(carved).toContain('class="piece-ground"')
    expect(carved).toContain('class="piece-lit"')
    expect(carved).toContain('class="piece-collar"')
    expect(carved).toContain('class="piece-plinth"')
    expect(carved).toContain('class="piece-waist"')
    expect(carved).toContain('class="piece-rim"')
    expect(carved).toContain('class="piece-neck"')
    expect(carved).toContain('class="piece-flute"')
    expect(carved).toContain('class="piece-umbra"')
    expect(carved).toContain('class="piece-cup"')
    expect(carved).toContain('class="piece-orb"')
    expect(carved).toContain('class="piece-spark"')
    expect(carved).toContain('class="piece-ferrule"')
    expect(carved).toContain('feSpecularLighting')
    expect(carved).toContain('feDiffuseLighting')
    expect(carved).toContain('linearGradient')
    expect(carved).toMatch(/fill="url\(#pl\d+g\)"/)
    expect(carved).toContain('rgba(255,255,255,0.36)')
    expect(carveGlyph(carved, 'w')).toBe(carved)
  })

  it('keeps lathe rings and lamp filters after HTML innerHTML', () => {
    const host = document.createElement('div')
    host.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'p')
    expect(host.querySelector('.piece-plinth')).toBeTruthy()
    expect(host.querySelector('.piece-waist')).toBeTruthy()
    expect(host.querySelector('.piece-rim')).toBeTruthy()
    expect(host.querySelector('.piece-neck')).toBeTruthy()
    expect(host.querySelector('.piece-flute')).toBeTruthy()
    expect(host.querySelector('.piece-umbra')).toBeTruthy()
    expect(host.querySelector('.piece-cup')).toBeTruthy()
    expect(host.querySelector('.piece-orb')).toBeTruthy()
    expect(host.querySelector('.piece-spark')).toBeTruthy()
    expect(host.querySelector('.piece-ferrule')).toBeTruthy()
    const queenHost = document.createElement('div')
    queenHost.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'q')
    expect(queenHost.querySelectorAll('.piece-pearl')).toHaveLength(5)
    const rookHost = document.createElement('div')
    rookHost.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'r')
    expect(rookHost.querySelectorAll('.piece-merlon')).toHaveLength(2)
    const bishopHost = document.createElement('div')
    bishopHost.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'b')
    expect(bishopHost.querySelectorAll('.piece-cleft')).toHaveLength(2)
    const kingHost = document.createElement('div')
    kingHost.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'k')
    expect(kingHost.querySelectorAll('.piece-cross')).toHaveLength(2)
    const knightHost = document.createElement('div')
    knightHost.innerHTML = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'n')
    expect(knightHost.querySelectorAll('.piece-eye')).toHaveLength(1)
    expect(host.querySelector('feDiffuseLighting')).toBeTruthy()
    expect(host.querySelectorAll('fePointLight')).toHaveLength(3)
    expect(host.querySelectorAll('feSpecularLighting')).toHaveLength(2)
  })

  it('uses a gold sheen on black pieces', () => {
    expect(carveGlyph('<svg></svg>', 'b')).toContain('rgba(232,201,126,0.32)')
    expect(carveGlyph('<svg></svg>', 'b')).toContain('#7aa8d4')
  })

  it('gives each piece type a distinct sheen path', () => {
    const pawn = carveGlyph('<svg></svg>', 'w', 'p')
    const king = carveGlyph('<svg></svg>', 'w', 'k')
    const rook = carveGlyph('<svg></svg>', 'w', 'r')
    expect(pawn).not.toBe(king)
    expect(king).not.toBe(rook)
    expect(pawn).toContain('rx="8.4"')
    expect(rook).toContain('rx="11.4"')
    expect(pawn).toContain('cy="31.8"')
    expect(rook).toContain('cy="34.6"')
    expect(pawn).toContain('class="piece-neck"')
    expect(pawn).toContain('class="piece-plinth"')
    expect(pawn).toContain('class="piece-waist"')
    expect(pawn).toContain('class="piece-flute"')
    expect(pawn).toContain('class="piece-umbra"')
    expect(pawn).toContain('class="piece-cup"')
    expect(pawn).toContain('class="piece-orb"')
    expect(pawn).toContain('class="piece-spark"')
    expect(pawn).toContain('class="piece-ferrule"')
    expect(pawn).not.toContain('class="piece-mane"')
    expect(pawn).not.toContain('class="piece-eye"')
    expect(pawn).not.toContain('class="piece-pearl"')
    expect(pawn).not.toContain('class="piece-merlon"')
    expect(pawn).not.toContain('class="piece-cleft"')
    expect(pawn).not.toContain('class="piece-cross"')
    expect(pawn).toContain('cx="26.8"')
    expect(pawn).toContain('cy="35.1"')
    const knight = carveGlyph('<svg></svg>', 'w', 'n')
    expect(knight).toContain('class="piece-plinth"')
    expect(knight).toContain('class="piece-waist"')
    expect(knight).toContain('class="piece-flute"')
    expect(knight).toContain('class="piece-umbra"')
    expect(knight).not.toContain('class="piece-neck"')
    expect(knight).not.toContain('class="piece-cup"')
    expect(knight).not.toContain('class="piece-orb"')
    expect(knight).not.toContain('class="piece-spark"')
    expect(knight).toContain('class="piece-ferrule"')
    expect(knight).toContain('class="piece-mane"')
    expect(knight).toContain('class="piece-eye"')
    expect(knight).not.toContain('class="piece-pearl"')
    expect(knight).not.toContain('class="piece-merlon"')
    expect(knight).not.toContain('class="piece-cleft"')
    expect(knight).not.toContain('class="piece-cross"')
    const queen = carveGlyph('<svg></svg>', 'w', 'q')
    expect(queen).toContain('class="piece-pearl"')
    expect(queen).not.toContain('class="piece-merlon"')
    expect(queen).not.toContain('class="piece-cleft"')
    expect(queen).not.toContain('class="piece-cross"')
    expect(queen).not.toContain('class="piece-mane"')
    expect(queen).not.toContain('class="piece-eye"')
    expect(queen).not.toContain('class="piece-orb"')
    expect(queen).not.toContain('class="piece-spark"')
    expect(queen.match(/class="piece-pearl"/g)).toHaveLength(5)
    expect(queen).toContain('r="2.18"')
    expect(rook).toContain('class="piece-merlon"')
    expect(rook).not.toContain('class="piece-pearl"')
    expect(rook).not.toContain('class="piece-cleft"')
    expect(rook).not.toContain('class="piece-cross"')
    expect(rook).not.toContain('class="piece-mane"')
    expect(rook).not.toContain('class="piece-eye"')
    expect(rook).not.toContain('class="piece-orb"')
    expect(rook).not.toContain('class="piece-spark"')
    expect(rook.match(/class="piece-merlon"/g)).toHaveLength(2)
    const bishop = carveGlyph('<svg></svg>', 'w', 'b')
    expect(bishop).toContain('class="piece-cleft"')
    expect(bishop).not.toContain('class="piece-pearl"')
    expect(bishop).not.toContain('class="piece-merlon"')
    expect(bishop).not.toContain('class="piece-mane"')
    expect(bishop).not.toContain('class="piece-eye"')
    expect(bishop).not.toContain('class="piece-orb"')
    expect(bishop).not.toContain('class="piece-spark"')
    expect(bishop.match(/class="piece-cleft"/g)).toHaveLength(2)
    expect(bishop).not.toContain('class="piece-cross"')
    const kingGlyph = carveGlyph('<svg></svg>', 'w', 'k')
    expect(kingGlyph).toContain('class="piece-cross"')
    expect(kingGlyph).not.toContain('class="piece-pearl"')
    expect(kingGlyph).not.toContain('class="piece-merlon"')
    expect(kingGlyph).not.toContain('class="piece-cleft"')
    expect(kingGlyph).not.toContain('class="piece-mane"')
    expect(kingGlyph).not.toContain('class="piece-eye"')
    expect(kingGlyph).not.toContain('class="piece-orb"')
    expect(kingGlyph).not.toContain('class="piece-spark"')
    expect(kingGlyph.match(/class="piece-cross"/g)).toHaveLength(2)
  })

  it('sizes the pawn globe catch-light to read on a phone square', () => {
    const pawn = carveGlyph('<svg></svg>', 'w', 'p')
    const orbR = Number(pawn.match(/class="piece-orb"[^/]*r="([\d.]+)"/)?.[1])
    const sparkR = Number(pawn.match(/class="piece-spark"[^/]*r="([\d.]+)"/)?.[1])
    expect(orbR).toBeGreaterThanOrEqual(2.6)
    expect(sparkR).toBeGreaterThanOrEqual(1.45)
    expect(sparkR).toBeLessThan(orbR)
  })

  it('sizes the knight eye to read on a phone square', () => {
    const knight = carveGlyph('<svg></svg>', 'w', 'n')
    const eyeR = Number(knight.match(/class="piece-eye"[^/]*r="([\d.]+)"/)?.[1])
    expect(eyeR).toBeGreaterThanOrEqual(1.6)
  })

  it('sizes queen coronet pearls to read on a phone square', () => {
    const queen = carveGlyph('<svg></svg>', 'w', 'q')
    const pearlR = Number(queen.match(/class="piece-pearl"[^/]*r="([\d.]+)"/)?.[1])
    expect(pearlR).toBeGreaterThanOrEqual(2.1)
  })

  it('sizes the king cross inlay to read on a phone square', () => {
    const kingGlyph = carveGlyph('<svg></svg>', 'w', 'k')
    const widths = [...kingGlyph.matchAll(/class="piece-cross"[^>]*width="([\d.]+)"/g)].map((m) => Number(m[1]))
    const heights = [...kingGlyph.matchAll(/class="piece-cross"[^>]*height="([\d.]+)"/g)].map((m) => Number(m[1]))
    expect(widths[0]).toBeGreaterThanOrEqual(2.5)
    expect(heights[1]).toBeGreaterThanOrEqual(3.2)
  })

  it('sizes the bishop mitre cleft to read on a phone square', () => {
    const bishop = carveGlyph('<svg></svg>', 'w', 'b')
    const widths = [...bishop.matchAll(/class="piece-cleft"[^>]*width="([\d.]+)"/g)].map((m) => Number(m[1]))
    const heights = [...bishop.matchAll(/class="piece-cleft"[^>]*height="([\d.]+)"/g)].map((m) => Number(m[1]))
    expect(widths[0]).toBeGreaterThanOrEqual(2.3)
    expect(heights[1]).toBeGreaterThanOrEqual(3.2)
  })

  it('sizes rook merlon wells to read on a phone square', () => {
    const rook = carveGlyph('<svg></svg>', 'w', 'r')
    const heights = [...rook.matchAll(/class="piece-merlon"[^>]*height="([\d.]+)"/g)].map((m) => Number(m[1]))
    expect(heights[0]).toBeGreaterThanOrEqual(4.5)
    expect(heights[1]).toBeGreaterThanOrEqual(4.5)
  })

  it('sizes the rook battlement cup to read on a phone square', () => {
    const rook = carveGlyph('<svg></svg>', 'w', 'r')
    const ry = Number(rook.match(/class="piece-cup"[^>]*ry="([\d.]+)"/)?.[1])
    expect(ry).toBeGreaterThanOrEqual(2.2)
  })

  it('sizes the king crown cup to read on a phone square', () => {
    const kingGlyph = carveGlyph('<svg></svg>', 'w', 'k')
    const ry = Number(kingGlyph.match(/class="piece-cup"[^>]*ry="([\d.]+)"/)?.[1])
    expect(ry).toBeGreaterThanOrEqual(2.2)
  })

  it('sizes the queen coronet cup to read on a phone square', () => {
    const queen = carveGlyph('<svg></svg>', 'w', 'q')
    const ry = Number(queen.match(/class="piece-cup"[^>]*ry="([\d.]+)"/)?.[1])
    expect(ry).toBeGreaterThanOrEqual(2.2)
  })

  it('sizes the foot ferrule to read on a phone square', () => {
    const pawn = carveGlyph('<svg></svg>', 'w', 'p')
    const ry = Number(pawn.match(/class="piece-ferrule"[^>]*ry="([\d.]+)"/)?.[1])
    expect(ry).toBeGreaterThanOrEqual(1.45)
  })

  it('assigns unique lamp ids so neighboring glyphs do not clash', () => {
    const a = carveGlyph('<svg fill="var(--piece-fill)"></svg>', 'w', 'p')
    const b = carveGlyph('<svg fill="var(--piece-fill)"></svg>', 'w', 'p')
    const idA = a.match(/url\(#(pl\d+f)\)/)?.[1]
    const idB = b.match(/url\(#(pl\d+f)\)/)?.[1]
    expect(idA).toBeTruthy()
    expect(idB).toBeTruthy()
    expect(idA).not.toBe(idB)
  })

  it('skips specular lighting when visual quality is forced lean', () => {
    const prev = globalThis.localStorage?.getItem('cok-visual-quality')
    globalThis.localStorage?.setItem('cok-visual-quality', 'lean')
    try {
      const carved = carveGlyph('<svg><path fill="var(--piece-fill)" d="M1"/></svg>', 'w', 'p')
      expect(carved).toContain('class="piece-lit"')
      expect(carved).toContain('linearGradient')
      expect(carved).not.toContain('feSpecularLighting')
      expect(carved).not.toContain('feDiffuseLighting')
      expect(carved).toContain('class="piece-plinth"')
      expect(carved).toContain('class="piece-waist"')
      expect(carved).toContain('class="piece-flute"')
      expect(carved).toContain('class="piece-umbra"')
      expect(carved).toContain('class="piece-cup"')
      expect(carved).toContain('class="piece-orb"')
      expect(carved).toContain('class="piece-spark"')
      expect(carved).toContain('class="piece-ferrule"')
      expect(carved).not.toContain('class="piece-mane"')
      expect(carveGlyph('<svg></svg>', 'w', 'n')).toContain('class="piece-eye"')
      expect(carveGlyph('<svg></svg>', 'w', 'q')).toContain('class="piece-pearl"')
      expect(carveGlyph('<svg></svg>', 'w', 'r')).toContain('class="piece-merlon"')
      expect(carveGlyph('<svg></svg>', 'w', 'b')).toContain('class="piece-cleft"')
      expect(carveGlyph('<svg></svg>', 'w', 'k')).toContain('class="piece-cross"')
      expect(carved).not.toContain(' filter=')
    } finally {
      if (prev == null) globalThis.localStorage?.removeItem('cok-visual-quality')
      else globalThis.localStorage?.setItem('cok-visual-quality', prev)
    }
  })
})

describe('glyphForSkin', () => {
  it('carves classic royal ivory and lapis pieces with lamp lighting', () => {
    const pawn = glyphForSkin('classic-royal', 'w', 'p')
    expect(pawn).toContain('class="svg-piece"')
    expect(pawn).toContain('piece-carve')
    expect(pawn).toContain('piece-foot')
    expect(pawn).toContain('piece-ground')
    expect(pawn).toContain('piece-lit')
    expect(pawn).toContain('piece-collar')
    expect(pawn).toContain('piece-plinth')
    expect(pawn).toContain('piece-waist')
    expect(pawn).toContain('piece-rim')
    expect(pawn).toContain('piece-neck')
    expect(pawn).toContain('piece-flute')
    expect(pawn).toContain('piece-umbra')
    expect(pawn).toContain('piece-cup')
    expect(pawn).toContain('piece-orb')
    expect(pawn).toContain('piece-spark')
    expect(pawn).toContain('piece-ferrule')
    expect(pawn).not.toContain('piece-mane')
    expect(pawn).not.toContain('piece-eye')
    expect(pawn).not.toContain('piece-pearl')
    expect(pawn).not.toContain('piece-merlon')
    expect(pawn).not.toContain('piece-cleft')
    expect(pawn).not.toContain('piece-cross')
    expect(glyphForSkin('classic-royal', 'w', 'q')).toContain('piece-pearl')
    expect(glyphForSkin('classic-royal', 'w', 'r')).toContain('piece-merlon')
    expect(glyphForSkin('classic-royal', 'w', 'b')).toContain('piece-cleft')
    expect(glyphForSkin('classic-royal', 'w', 'k')).toContain('piece-cross')
    expect(glyphForSkin('classic-royal', 'w', 'n')).toContain('piece-eye')
    expect(pawn).toContain('feSpecularLighting')
    expect(pawn).toContain('feDiffuseLighting')
    expect(glyphForSkin('alexandrine-ornate', 'b', 'k')).toContain('piece-carve')
  })

  it('leaves high-contrast glyphs uncarved for tournament readability', () => {
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-carve')
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-lit')
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-umbra')
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-cup')
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-ferrule')
    expect(glyphForSkin('high-contrast', 'w', 'n')).not.toContain('piece-mane')
    expect(glyphForSkin('high-contrast', 'w', 'n')).not.toContain('piece-eye')
    expect(glyphForSkin('high-contrast', 'w', 'q')).not.toContain('piece-pearl')
    expect(glyphForSkin('high-contrast', 'w', 'r')).not.toContain('piece-merlon')
    expect(glyphForSkin('high-contrast', 'w', 'b')).not.toContain('piece-cleft')
    expect(glyphForSkin('high-contrast', 'w', 'k')).not.toContain('piece-cross')
    expect(glyphForSkin('high-contrast', 'w', 'p')).not.toContain('piece-orb')
    expect(glyphForSkin('high-contrast', 'w', 'p')).not.toContain('piece-spark')
  })
})
